### PR TITLE
op04n03 update to 2.3.0

### PR DESCRIPTION
**Pull request by adriannagel**

### CODE REVIEW

**Review by davor-k — APPROVED** [review]
just one very small change, otherwise ready to merge

**Comment by davor-k** [comment]
@adriannagel Hey Adrian, is this one PR for all 4 movements? I only reviewed the first one

**Comment by adriannagel** [comment]
> @adriannagel Hey Adrian, is this one PR for all 4 movements? I only reviewed the first one

Yes it is for all movements!

**Comment by davor-k** [comment]
@adriannagel okay, now it's all ready! thanks

**Comment by adriannagel** [comment]
@johentsch there is a problem with conflicting files?

**Comment by johentsch** [comment]
Just because this PR has been open for a year :-) Now it's fixed

**Pull request merged**
