### PR TITLE
Fully annotated Op03n04c.

### PR DESCRIPTION
**Pull request by yrammos**

### CODE REVIEW

**Comment by johentsch** [comment]
Hey @yrammos, just had a look at the beginning but need to stop for now. Happy to discuss already if there is need. Just as a preview: From m. 11 at the latest I feel in the key of III but haven't made up my mind where to put the key change. In the most extreme version it would even be with the new phrase in m. 9. Let me know what you think and have a lovely weekend!

**Comment by johentsch** [comment]
Continued until m. 30

**Comment by johentsch** [comment]
done, would be fine from my side

**Comment by yrammos** [comment]
@johentsch thanks for this. Our annotations attempt to represent harmony at different levels of structure. With the theoretical provisos we discussed in private, I adopt all your revisions, since they are aligned with the practice already applied across DCML corpora.

**Pull request merged**
